name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    name: Release on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux
          - os: macos-latest
            platform: mac
          - os: windows-latest
            platform: win
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: |
        npm ci
        cd packages/renderer
        npm ci
        cd ../..
    
    - name: Build and Package (macOS)
      if: matrix.platform == 'mac'
      run: npm run package:mac
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Build and Package (Windows)
      if: matrix.platform == 'win'
      run: npm run package:win
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Build and Package (Linux)
      if: matrix.platform == 'linux'
      run: npm run package:linux
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Upload Release Assets
      uses: softprops/action-gh-release@v1
      with:
        files: |
          release/*.dmg
          release/*.zip
          release/*.exe
          release/*.msi
          release/*.AppImage
          release/*.deb
          release/*.rpm
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
